---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
  {{ include "labels" . | indent 4 | trim }}
data:
  HTTP_PORT: "{{ .Values.configmap.http_port }}"
  DEBUG: "{{ .Values.configmap.debug }}"
  LOG_LEVEL: "{{ .Values.configmap.log_level }}"

