---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    component: "api"
  {{ include "labels" . | indent 4 | trim }}
spec:
  ports:
    - name: "http"
      port: 80
      protocol: TCP
      targetPort: {{ .Values.configmap.http_port }}
  selector:
    instance: "{{ .Release.Name }}"
    component: "api"
  sessionAffinity: None
  type: ClusterIP
