---
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: "deployment-{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
  {{ include "labels" . | indent 4 | trim }}